
CREATE TABLE IF NOT EXISTS tempTable
(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL DEFAULT (0),
    int_value INTEGER NOT NULL DEFAULT (0),
    real_value REAL NOT NULL DEFAULT (0),
    text_value TEXT NOT NULL
);