#ifndef FIREWORKS_QPAINTERBACKEND_H
#define FIREWORKS_QPAINTERBACKEND_H

#include <QtCore/qglobal.h>

#if defined(QPAINTER_FIREWORKS_BACKEND)
#  define QPAINTERBACKEND_EXPORT Q_DECL_EXPORT
#else
#  define QPAINTERBACKEND_EXPORT Q_DECL_IMPORT
#endif

#endif // FIREWORKS_QPAINTERBACKEND_H
