#ifndef FW_BACKEND_QPAINTER_H
#define FW_BACKEND_QPAINTER_H

#include <QtCore/qglobal.h>

#if defined(FW_BACKEND_QPAINTER_LIBRARY)
#  define FW_BACKEND_QPAINTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FW_BACKEND_QPAINTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif //FW_BACKEND_QPAINTER_H

